### ISSUE TITLE
How to get BLEU4 larger than 30 with BART-large in Adgen ?

### ISSUE THREAD

**Issue by MiuJackson** [fastnlp/CPT#1]
您好，
     想咨询您提供的BART模型是如何达到30以上的BLEU值，是将所有输入包括title、feature序列化之后直接输入encoder，desc在decoder端么？还是做了什么特殊处理。我用BART只能到10左右的BLEU，感谢回复。

**Comment by fdugzc** [comment]
我们在 finetune/generation 目录里放了一些数据样例、运行代码、生成结果，您可以看下是哪个环节导致的

**Comment by MiuJackson** [comment]
> 我们在 finetune/generation 目录里放了一些数据样例、运行代码、生成结果，您可以看下是哪个环节导致的

非常感谢回复以及开源的模型和代码，我学习一下，看我们差在了哪里。

**Comment by MiuJackson** [comment]
您好，
      我大概知道是哪里有区别了，我在算BLEU的时候是没有算空格的：
![image](https://user-images.githubusercontent.com/74551247/134849808-93e2af23-3061-4b28-ab30-d728362251a1.png)
     代码里算BLEU时是有算空格的，
![image](https://user-images.githubusercontent.com/74551247/134849834-062e684b-aa23-443f-b36a-daa4e9033a28.png)
    我的理解是此时是否不能把空格的正确计算在内，包括CPM2在内的paper算BLEU-4应该是只算有效字符的。

**Comment by MiuJackson** [comment]
![image](https://user-images.githubusercontent.com/74551247/134849970-1edc0943-0826-4948-833c-b7780af2631f.png)
![image](https://user-images.githubusercontent.com/74551247/134850013-574ff4c5-22f5-4a60-b287-2892b54438e4.png)

**Comment by fdugzc** [comment]
这个确实是我们的疏忽了，这里要把句子转成list输入进去，我们会尽快更新论文中的结果的，谢谢您的指正：）

**Comment by MiuJackson** [comment]
👍🏻也多谢回复
