### ISSUE TITLE
BART中文模型，有试过seq2seq的方式在中文NER任务上的效果吗？比如你们组的ACL工作BARTNER。

### ISSUE THREAD

**Issue by loujie0822** [fastnlp/CPT#10]
BART中文模型，有试过seq2seq的方式在中文NER任务上的效果吗？比如你们组的ACL工作BARTNER。

**Comment by choosewhatulike** [comment]
我们试过BARTNER的方式，模型BART和CPT都试过了，效果相比直接fine-tune要差一点点。一个是我们超参也没怎么调，还有就是我们怀疑中文的tokenization导致了长序列问题，生成起来比英文要难。
