### ISSUE TITLE
generation/LCSTS数据集上效果没达到

### ISSUE THREAD

**Issue by zhoucz97** [fastnlp/CPT#13]
您好，我最近在LCSTS数据集上跑了您的代码，结果只有`rouge-L：31`，论文给的结果是38左右，差很多。

数据集直接在网上下载然后处理成如下格式：
```
{"summarization": "可穿戴技术十大设计原则", "article": "本文总结了十个可穿戴产品的设计原则，而这些原则，同样也是笔者认为是这个行业最吸引人的地方：1.为人们解决重复性问题；2.从人开始，而不是从机器开始；3.要引起注意，但不要刻意；4.提升用户能力，而不是取代人"}
```
代码只修改了文件路径，其余无改动。
请问问题可能出在哪里呢？
run_gen.py中的默认超参数，是否是最优的超参数呢？

**Comment by zhoucz97** [comment]
另外问一下，您是用几块卡跑的生成任务的微调？

**Comment by fdugzc** [comment]
用run_gen.py中的参数也能复现的，差7个点的话肯定不是超参的问题了。我能想到的地方有：1. lcsts数据集的测试集是否是part III中score大于等于3的sample？2.使用的ROUGE包是不是 https://github.com/pltrdy/rouge 里的rouge？
我们跑生成微调的时候一般是1-2块卡

**Comment by zhoucz97** [comment]
感谢您的回复，极有可能是数据集的问题，由于我是第一次接触这个数据集，并不知道要用score>3的部分数据，我再测试一下试一试，感谢~~~~

**Comment by fdugzc** [comment]
没事的，https://arxiv.org/abs/1506.05865 这里有一些对论文的介绍 （我们用的训练数据是part I 中的全部sample，没有筛选，part III使用了score>=3的样本）

**Comment by fdugzc** [comment]
没事的，https://arxiv.org/abs/1506.05865 这里有一些对数据集的介绍 （我们用的训练数据是part I 中的全部sample，没有筛选，part III使用了score>=3的样本）

**Comment by zhoucz97** [comment]
> 没事的，https://arxiv.org/abs/1506.05865 这里有一些对数据集的介绍 （我们用的训练数据是part I 中的全部sample，没有筛选，part III使用了score>=3的样本）

好的！太谢谢啦！😊😊

**Comment by zhoucz97** [comment]
> 没事的，https://arxiv.org/abs/1506.05865 这里有一些对数据集的介绍 （我们用的训练数据是part I 中的全部sample，没有筛选，part III使用了score>=3的样本）

想再确认一下，您是用part I 全部样本做训练，part II全部样本做验证，part III scores>=3的样本做预测是吗？

**Comment by fdugzc** [comment]
> > 没事的，https://arxiv.org/abs/1506.05865 这里有一些对数据集的介绍 （我们用的训练数据是part I 中的全部sample，没有筛选，part III使用了score>=3的样本）
> 
> 想再确认一下，您是用part I 全部样本做训练，part II全部样本做验证，part III scores>=3的样本做预测是吗？

准确说，是使用part 1随机划分的80%数据训练，20%数据验证（后又发现20%验证时间太久，就又从20%数据中划分3万条做验证）。part 2的数据按论文描述也是来自part 1，就没有再管part 2

**Comment by zhoucz97** [comment]
> > > 没事的，https://arxiv.org/abs/1506.05865 这里有一些对数据集的介绍 （我们用的训练数据是part I 中的全部sample，没有筛选，part III使用了score>=3的样本）
> > 
> > 
> > 想再确认一下，您是用part I 全部样本做训练，part II全部样本做验证，part III scores>=3的样本做预测是吗？
> 
> 准确说，是使用part 1随机划分的80%数据训练，20%数据验证（后又发现20%验证时间太久，就又从20%数据中划分3万条做验证）。part 2的数据按论文描述也是来自part 1，就没有再管part 2

哦哦，这样啊，不知您是否方便提供一下处理好的数据集呢，我老师要求我复现一下结果hhhhh

**Comment by fdugzc** [comment]
留一下你的邮箱？我发给你

**Comment by zhoucz97** [comment]
> 留一下你的邮箱？我发给你

1059482037@qq.com.   非常感谢～～

**Comment by tiexueYL** [comment]
> > 留一下你的邮箱？我发给你
> 
> [1059482037@qq.com](mailto:1059482037@qq.com). 非常感谢～～

请问可不可以分享给我一份呢？多谢多谢 这是我的邮箱哈 ylajhb@163.com

**Comment by nuanyangchuncao** [comment]
请问分享给我一份可以嘛？非常感谢！lv_611@163.com

**Comment by MeloJames** [comment]
> 另外问一下，您是用几块卡跑的生成任务的微调？

大佬您好，不知您是否方便提供一下处理好的数据集呢

> 留一下你的邮箱？我发给你

大佬您好，请问方便分享一下处理好的数据集给我吗？ 非常感谢，方便的话麻烦发我邮箱491573089@qq.com

**Comment by fdugzc** [comment]
我把处理好的数据放百度网盘了
链接：https://pan.baidu.com/s/1VYbYTDLh_hWxnmDwf6T4wA 
提取码：njwk

**Comment by MeloJames** [comment]
谢谢大佬哈！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fastnlp/CPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fastnlp/CPT] generation/LCSTS数据集上效果没达到 (Issue #13)





 
我把处理好的数据放百度网盘了
 链接：https://pan.baidu.com/s/1VYbYTDLh_hWxnmDwf6T4wA
 提取码：njwk
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by josephcui** [comment]
作者您好，请问在LCSTS测试集上infer时的beam size设置为多少呀？

**Comment by fdugzc** [comment]
> 作者您好，请问在LCSTS测试集上infer时的beam size设置为多少呀？

是4
