### ISSUE TITLE
有关Decoder的层数问题

### ISSUE THREAD

**Issue by AQA6666** [fastnlp/CPT#15]
1. CPT中使用了非对称的Encoder-Decoder，您是如何确定这两者的层数比例的，有进行过不同比例的对比试验吗？
2. 在CPT的生成模式中，我有些担心G-Decoder的层数过小(2层)影响到生成的效果，因为深层Encoder的能力与G-Decoder的能力并不一致。也就是说，我认为G-Decoder的层数应该当更深一些，才能够根据Encoder编码的提示去推理应该生成的文字（U-Decoder不用更深是因为Encoder所做的事与其一致）（现有的生成模型的单向注意力层都相当的多）。这个问题您觉得可能会存在吗？有没有相关的实验？

**Comment by AQA6666** [comment]
我觉得U-Decoder两层的话，G-Decoder则需要四层甚至更多，因为对于生成来说，Encoder提供一个好的Prompt+上文的表示只是第一步，还需要更多的层数才能实现生成能力

**Comment by choosewhatulike** [comment]
实验下来CPT Base的两层和BART Base的6层decoder生成效果差不多，具体可以看我们论文的实验部分。
