### ISSUE TITLE
ner模型的问题

### ISSUE THREAD

**Issue by suhejian** [fastnlp/CPT#17]
按照您提供的运行指令
python -m torch.distributed.launch --nproc_per_node 1 --nnodes 1 \
    train_msra.py \
    --ptm_name fnlp/cpt-base \
    --dataset '' \
    --use_decoder 0 \
    --batch_size 16 \
    --update_every 1 
运行以后，会报如下错误：
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss.

**Comment by choosewhatulike** [comment]
可能是pytorch版本的问题，我用的pytorch==1.8.1, cuda11.1是能正常训练的

**Comment by suhejian** [comment]
好的，谢谢您的回复！我修改一下pytorch和cuda的版本号再重新试一下。


| |
hejiansu
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月20日 18:25，Yunfan ***@***.***> 写道：

可能是pytorch版本的问题，我用的pytorch==1.8.1, cuda11.1是能正常训练的

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tmsxk** [comment]
你好，我也出现了相似的问题，请问您解决了没

**Comment by suhejian** [comment]
你好，我修改了pytorch和cuda的版本号以后依旧无法复现，加上自己对fastNLP不熟悉，所以我参照源代码用pytorch重写了。目前在MSRA数据集上，用base CPT可以达到0.9564的F1分数，原论文的效果是0.9578.


| |
hejiansu
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月28日 ***@***.***> 写道：

你好，我也出现了相似的问题，请问您解决了没

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by choosewhatulike** [comment]
这个报错我无法复现，怀疑是环境不一样导致的，这是我用的：
FastNLP==0.6.0
torch==1.8.1
transformers==4.4.1
numpy==1.19.2
Python==3.7.10

**Comment by cnksyyy** [comment]
在代码里找了一下，是fastNLP.core.dist_trainer.py的第176行里
self.ddp_model = DDP(model, device_ids=[self.local_rank],
                                     output_device=self.local_rank,
                                     find_unused_parameters=kwargs.get('find_unused_parameters', False))
把这里的False改成True就可以正常运行了。
