### ISSUE TITLE
encoder decoder最大位置编码不一致

### ISSUE THREAD

**Issue by JaheimLee** [fastnlp/CPT#18]
Hello，我看cpt encoder部分默认使用bert模型，而config文件中的max_position_embedding仅在decoder部分生效，那encoder部分最大还是只支持512的长度，这很不合理啊。huggingface bart中encoder decoder编码长度是一直的。当前大多数seq2seq任务，除了data-to-text这种，都是encoder部分长度比decoder部分长度长很多，或者二者接近。现在decoder有1024，encoder仅有512，对下游seq2seq任务影响很大啊

**Comment by choosewhatulike** [comment]
这个是模型初始化不同造成的，BERT初始化默认512，BART默认1024长度。但我们预训CPT固定512长度，decoder后面的position embedding相当于一直是随机初始化的，所以fine-tune的时候保持512就好。

当然你也可以自己扩充encoder的position embedding，按照需求可能1024，2048等等都是可以的
