### ISSUE TITLE
有关bart-base-chinese的vocab.txt文件

### ISSUE THREAD

**Issue by Edward-Joker** [fastnlp/CPT#20]
您好，有关你们发布在huggingface的**bart-base-chinese**预训练模型，词表文件**vocab**是否有json格式的文件？恳请请告知。
--------因为facebook的vocab文件是json格式的，而你们发布的vocab文件是txt格式的

**Comment by Edward-Joker** [comment]
我看了你们写的使用文档，为何Bart-chinese的词表要使用BertTokenizer，是因为使用的Bert词表吗？

**Comment by choosewhatulike** [comment]
是的，CPT和BART都用的Bert的词表
