### ISSUE TITLE
max_position_embeddings是1024吗

### ISSUE THREAD

**Issue by awdrgyjilplij** [fastnlp/CPT#27]
我看fnlp/cpt-base里面config.json的max_position_embeddings写的1024，但实际上1024会报错，512没问题。
发现代码里用了BertModel当encoder，但是没设置对应的max_position_embeddings
手动改成1024会导致预训练参数加载不进来。
所以我的理解是config.json写错了，实际只支持512。希望能提供一版max_position_embeddings=1024的模型，和bart对齐一下

**Comment by choosewhatulike** [comment]
CPT目前只支持512最大句长，未来会提供1024的版本

**Comment by maojinyang** [comment]
请问现在还有提供1024版本模型的计划吗？
