### ISSUE TITLE
想咨询run_gen.py如何设置GPU运行？

### ISSUE THREAD

**Issue by PolarisRisingWar** [fastnlp/CPT#28]
您好！我直接运行 `whj_code1/projects/CPT/finetune/generation/run_gen.py` 代码，发现是用CPU运行的。我看到日志中输出了 `training_args.local_rank`、`training_args.device`、`training_args.n_gpu` 参数，但是我发现代码中没有提供传参的位置，而且我也无法直接通过args传递这些参数。所以想咨询如何修改代码，使其能够用GPU来运行呢？

**Comment by PolarisRisingWar** [comment]
是我的环境出现了问题。目前已解决。

**Comment by Richar-Du** [comment]
您好，我也出现了这样的问题，CLUE里的任务是可以用GPU运行的，但是run_gen.py不可以。请问您是怎么解决的呢？

**Comment by murray-z** [comment]
@PolarisRisingWar  你是怎么解决的呢？我也遇到了同样的问题。。。。

**Comment by Jxh99** [comment]
> 



> @PolarisRisingWar 你是怎么解决的呢？我也遇到了同样的问题。。。。
请问你解决了吗
