### ISSUE TITLE
Hardware and computing cost

### ISSUE THREAD

**Issue by Richar-Du** [fastnlp/CPT#29]
Could you tell the hardware you pre-trained the CPT and BART-chinese? And how long does it take to pre-train these models?

Thanks~

**Comment by choosewhatulike** [comment]
We trained models on 32 V100 32GB GPUs. For the base version, it takes almost a week. And for the large models, it takes roughly 3 weeks. For the hyperparameters, please check our paper.

**Comment by Richar-Du** [comment]
Got it :) Thanks for your kind reply.
