### ISSUE TITLE
生成任务的数据

### ISSUE THREAD

**Issue by Richar-Du** [fastnlp/CPT#32]
您好，官网上下载的数据格式和模型需要的输入不一致，麻烦您可以也发一下代码能接收的csl和adgen的数据吗？十分感谢～

_Originally posted by @fdugzc in https://github.com/fastnlp/CPT/issues/13#issuecomment-1006350187_

**Comment by fdugzc** [comment]
链接：https://pan.baidu.com/s/1ULhGNP9tqJOEaNIE_CE5Pw 
提取码：k8t1
