### ISSUE TITLE
classification/CLUEWSC 2020数据集上效果没达到 

### ISSUE THREAD

**Issue by zisang0210** [fastnlp/CPT#34]
您好，我最近在CLUEWSC 2020数据集上跑了您的代码，CPT_u (B) 、CPT_g (B) 、CPT_ug (B) 的准确率分别是87.82、86.84、85.52，而论文给的结果是91.1、87.2、89.8。请问是训练参数，数据预处理，数据集下载或者其它哪方面的问题？

**Comment by choosewhatulike** [comment]
这个数据集本身较小，结果波动较大很正常，推荐再调一调超参多实验几次

**Comment by choosewhatulike** [comment]
这是论文所使用超参，仅供参考：batch size 8, learning rate 2e-5, epoch 50, warmup ratio 0.06
