### ISSUE TITLE
Why g-dec will inflect the performance of u-dec?

### ISSUE THREAD

**Issue by Chen-Wang-CUHK** [fastnlp/CPT#35]
I am using the `u-dec` to perform a sequence labeling task. I found the code has to run the `g-dec` pass. Then I manually skip the `g-dec` pass since I do not need it. However, the performance of `u-dec` seems changed. From my understanding, they should be independent,  right? Are there any thoughts about this problem? Thank you.

**Comment by choosewhatulike** [comment]
Yes, they are independent. If the g-dec is not used for computing loss and inference, it would not affect the performance when removed. Perhapse removing the g-dec affects the random state of the initialization of parameters, which could make results changed for a bit.
