### ISSUE TITLE
pretrain任务的环境版本

### ISSUE THREAD

**Issue by 1190303311** [fastnlp/CPT#38]
使用bart的pretrain部分code时出现了一些问题，想问一下需要以下环境版本都是多少呢？：
torch版本
cuda版本
gcc版本
非常感谢！

**Comment by choosewhatulike** [comment]
我使用的是nvidia提供的docker环境，参见：https://github.com/fastnlp/CPT/blob/master/pretrain/README_megatron.md#setup
