### ISSUE TITLE
CSL摘要数据集没达到效果。

### ISSUE THREAD

**Issue by josephcui** [fastnlp/CPT#44]
作者您好，请问CSL摘要数据集你们训练了多少epoch呢？我们复现时ROUGE指标差的有点多。可以提供下微调细节吗，万分感谢！

**Comment by webdxq** [comment]
请问你们用的CSL是哪个数据集呢？是训练样本只有3000条的那个吗？数据集能分享下吗？

**Comment by webdxq** [comment]
这是来自QQ邮箱的自动回复邮件。您好~您发送的邮件我已收到。谢谢您的邮件~

**Comment by webdxq** [comment]
这是来自QQ邮箱的自动回复邮件。您好~您发送的邮件我已收到。谢谢您的邮件~

**Comment by webdxq** [comment]
这是来自QQ邮箱的自动回复邮件。您好~您发送的邮件我已收到。谢谢您的邮件~
