### ISSUE TITLE
bart-base-chinese支持 lightseq等推理加速不

### ISSUE THREAD

**Issue by ImmortalZ** [fastnlp/CPT#51]
你好，想咨询下 bart-base-chinese支持 lightseq等推理加速不，支持的话，有无类似的代码可供参考呢？

lightseq：https://github.com/bytedance/lightseq

**Comment by ImmortalZ** [comment]
已跑通

**Comment by runningabcd** [comment]
> https://github.com/bytedance/lightseq

说下结论
