### ISSUE TITLE
你好，想请教下微调中dev.json数据的结构问题？

### ISSUE THREAD

**Issue by ImmortalZ** [fastnlp/CPT#52]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/14830574/183291757-89dd00d2-34a5-40cd-be68-19ecf3a74b05.png">
比较奇怪为啥 article 中的是 [[x1,x2], [y1, y2]] 这样的字符串呢？

小白，看微调代码这里有点懵逼

**Comment by choosewhatulike** [comment]
这个数据集（adgen）目标就是给一些关键词生成广告语。article和summarization分别对应模型的输入和输出，这是为了不同数据集都能兼容一套生成代码，你也可以命名为input，output

**Comment by ImmortalZ** [comment]
> 这个数据集（adgen）目标就是给一些关键词生成广告语。article和summarization分别对应模型的输入和输出，这是为了不同数据集都能兼容一套生成代码，你也可以命名为input，output

@choosewhatulike 感觉解答，还想请教下，如果我想自定义数据微调，也是需要构造  [[x1,x2], [y1, y2]] 这样的字符串，还是article用普通的一句话这种也行的呢?（我看微调代码没有找到对 [[x1,x2], [y1, y2]] 这样的字符串 结构的处理，似乎普通的一句话也行）
