### ISSUE TITLE
ModuleNotFoundError: No module named 'amp_C'

### ISSUE THREAD

**Issue by aidejieceng** [fastnlp/CPT#57]
作者，您好
我尝试在自己的数据集上对CPT模型进行进一步pretrain时，当我从https://github.com/NVIDIA/apex下载apex，使用pip install -v --disable-pip-version-check --no-cache-dir ./ 进行安装，但会报错：ModuleNotFoundError: No module named 'amp_C'。
这个环境问题该怎么解决？

**Comment by choosewhatulike** [comment]
可能apex更新过，我当时用的docker image，参考这个：https://github.com/fastnlp/CPT/blob/master/pretrain/README_megatron.md#setup
