### ISSUE TITLE
CPT多GPU卡finetuning训练报错

### ISSUE THREAD

**Issue by aidejieceng** [fastnlp/CPT#58]
设置完模型参数后，使用python -m torch.distributed.launch --nproc_per_node 4 run_gen.py报错，local_rank需要作为参数进行传入，若parser.add_argument中增加--local_rank传入参数，整体多GPU训练报错。请问该如何对CPT进行多GPU卡的finetuning。恳求大佬给一份官方的使用说明！！感谢！

**Comment by choosewhatulike** [comment]
你的pytorch版本是多少，最新版1.13需要改成 torchrun --nproc_per_node 4 run_gen.py来运行

**Comment by aidejieceng** [comment]
@choosewhatulike 我在1.8.1和1.12.0两个版本上都试了，报出相同的错误！

**Comment by aidejieceng** [comment]
@choosewhatulike 不知能否官方给出使用示例，我目前的训练数据有500W，单卡训练太慢了

**Comment by choosewhatulike** [comment]
试了一下，直接python run_gen.py就可以，默认使用所有卡

**Comment by runningabcd** [comment]
> @choosewhatulike 不知能否官方给出使用示例，我目前的训练数据有500W，单卡训练太慢了

解决了吗？哈哈，多卡依然很慢，GPU 利用率很低
