### ISSUE TITLE
bart-base模型ft之前preprocess的方法是什么呢？

### ISSUE THREAD

**Issue by fubuki75** [fastnlp/CPT#60]
bart-base模型ft之前preprocess的方法是什么呢？我看仓库中没有提到ft前对中文数据的预处理

**Comment by choosewhatulike** [comment]
生成任务的话，一般只需要tokenize就行，参考ft下generation中的参考数据集

**Comment by fubuki75** [comment]
好的，感谢~
&nbsp;
------------------

siyuan.chen
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Yunfan Shao"; 
Sendtime: Wednesday, Dec 28, 2022 8:23 PM
To: "fastnlp/CPT"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [fastnlp/CPT] bart-base模型ft之前preprocess的方法是什么呢？ (Issue #60)





 
生成任务的话，一般只需要tokenize就行，参考ft下generation中的参考数据集
