### ISSUE TITLE
can I change the max length of csl

### ISSUE THREAD

**Issue by Dlinuigh** [fastnlp/CPT#63]
in finetune/run_gen.py, defines in a dict, 
``` python
length_map={'lcsts':'30','csl':'50','adgen':'128'}
```
but I want to process some sentences with max_length 512.

**Comment by choosewhatulike** [comment]
length_map defines the maximum length of generated tokens. It depends on the dataset you are using. The max_length of input texts is 1024 (in the updated version)

**Comment by lhz9999** [comment]
May I inquire if your latest CPT version can support the summarization of input texts with a length of 1,024 characters?
