### ISSUE TITLE
bug : got an unexpected keyword argument 'tokenizer_class'

### ISSUE THREAD

**Issue by xuefeich** [fastnlp/CPT#73]
from modeling_cpt import CPTForConditionalGeneration 报错了
请问下这个报错是什么原因呀
File "/tagmodel/task/modeling_cpt.py", line 867, in CPTModel
config_class=_CONFIG_FOR_DOC,
TypeError: add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'

**Comment by Ruby-G0** [comment]
transformers新版本的问题，把tokenizer_class替换成processor_class就行了
