### ISSUE TITLE
使用 CPT 进行微调后，生成任务推理很慢，一条数据都要好几秒，如何提升推理速度？

### ISSUE THREAD

**Issue by runningabcd** [fastnlp/CPT#79]
请问如何提升推理速度呢？
我尝试了多进程，但是收益并不明显，是否可以从底层进行改造，进而实现推理加速呢

**Comment by choosewhatulike** [comment]
这里的代码是2年前的，现在可以使用优化kernel（如flash attention），剪枝，量化等方式加速推理。
