### ISSUE TITLE
cpt有两个decoder吗

### ISSUE THREAD

**Issue by renmada** [fastnlp/CPT#8]
代码和权重里貌似都没有看到

**Comment by choosewhatulike** [comment]
CPT是由一个shared encoder 和两个decoder（understanding decoder和generation decoder）组成的。其中understanding decoder是双向attention，单层和shared encoder的结构一样，所以这两个模块在代码里当作一个整体写了（就如下面的BertModel，前面层是shared encoder，后面层是understanding decoder)。
https://github.com/fastnlp/CPT/blob/a1557684135c7d404c89501c825e234b01eba54f/finetune/modeling_cpt.py#L833
另一个decoder（generation decoder）就是正常做生成时的decoder了。

**Comment by renmada** [comment]
> CPT是由一个shared encoder 和两个decoder（understanding decoder和generation decoder）组成的。其中understanding decoder是双向attention，单层和shared encoder的结构一样，所以这两个模块在代码里当作一个整体写了（就如下面的BertModel，前面层是shared encoder，后面层是understanding decoder)。
> 
> https://github.com/fastnlp/CPT/blob/a1557684135c7d404c89501c825e234b01eba54f/finetune/modeling_cpt.py#L833
> 
> 
> 另一个decoder（generation decoder）就是正常做生成时的decoder了。

以下是我的理解，请帮忙确认对不对
BertModel 假设12层，前2层是 encoder，后10层是understanding decoder
**关于分类任务**
`        if cls_mode == 1:
            logger.info('Encoder for classification.')
            cls_dim = config.d_model
        elif cls_mode == 2:
            logger.info('Decoder for classification.')
            cls_dim = config.d_model
        elif cls_mode == 3:
            logger.info('Both encoder & decoder for classification.')
            cls_dim = config.d_model * 2`
这里的cls_mode=1实际上用的是understanding decode

**关于生成任务**
从代码看，用的是整个bert model 作为encoder，好像与论文里的图不相符
![Uploading image.png…]()

**Comment by choosewhatulike** [comment]
> 1. BertModel 假设12层，前2层是 encoder，后10层是understanding decoder

BertModel 12 层，前10层encoder，后2层understanding decoder。

> 2. 这里的cls_mode=1实际上用的是understanding decode

是的，`cls_mode=1, 2, 3` 分别对应论文里CPTu, CPTg, CPTug

> 3. 从代码看，用的是整个bert model 作为encoder，好像与论文里的图不相符

和论文里一样的，注意看这一行
https://github.com/fastnlp/CPT/blob/a1557684135c7d404c89501c825e234b01eba54f/finetune/modeling_cpt.py#L926
encoder_outputs[1] 是encoder所有层的输出，假设12层，我们会取第10层的输出给decoder
