### ISSUE TITLE
token_type_ids问题

### ISSUE THREAD

**Issue by JaheimLee** [fastnlp/CPT#9]
为什么在encoder端没有看到token_type_ids的传递呢，如果要做句子对分类问题我需重新修改源码啊？而且，CPTModel类里面encoder token_type_ids默认为什么给1啊？
https://github.com/fastnlp/CPT/blob/a1557684135c7d404c89501c825e234b01eba54f/finetune/modeling_cpt.py#L908

**Comment by choosewhatulike** [comment]
CPT其实用不到 token_type_ids，而是用 [SEP] 隔开来区分多句话。句对分类就在A句和B句之间加 [SEP] 就行。token_type_ids=1 这个在pre-train的时候就固定了，之后就没有改。

**Comment by kk19990709** [comment]
那huggingface上提供的BART需要 token_type_ids吗？这边看到报错`TypeError: forward() got an unexpected keyword argument 'token_type_ids'`
